### PR TITLE
Start i18n

### PR DESCRIPTION
**Pull request by drusepth**
Moving https://github.com/drusepth/Indent/pull/446 over here.

Added a couple commits for a small bug, automatic translations on form row generation, and the views for Equipment, but this is still a very WIP PR. :ship: 

cc @Cantido :)

### CODE REVIEW

**Comment by Cantido** [comment]
Sorry I kinda stopped doing this, it was super tedious lmao

I'll try and get back to this real soon. I've been working on [my own rails app](https://github.com/Cantido/toaster) and I've learned a lot about how much work Rails does for you with regard to l10n.

**Comment by drusepth** [comment]
Haha, no worries at all. Sorry I disappeared (for work) for a couple months. I did just a few files to try to help out and realized just how tedious this must have been. 

As you've no doubt noticed, I restructured a few more projects into this group repo bundle, but I'm planning on jumping back into the fray here and doing much more in the near future, and getting back to hiring some freelancers to help out with the other projects. Should be fun! :)

**Comment by drusepth** [comment]
(And I'll take a look at the repo when I'm not on a phone! :) )

**Comment by Cantido** [comment]
Should we abandon this PR? Since you overhauled the site, I don't think any of this work is still valid. And I'm embarassed by not having finished this yet :sweat:

**Comment by Cantido** [comment]
Closing. Too much has changed, and I learned a lot since I started, I think it would be better to scrap this and start from scratch.

**Pull request closed without merging**
