### PR TITLE
Content expansion release

### PR DESCRIPTION
**Pull request by drusepth**
Working through [the project](https://github.com/indentlabs/notebook/projects/3). Any PRs implementing any of the following should PR into the `content-expansion` branch rather than `master`, so we can release it all at once.
- [x] Redesign navbar UI to use new sidebar for content (to allow for more content types)
- [x] Plan Creatures
- [x] Plan Races
- [x] Plan Religions
- [x] Plan Magic
- [x] Plan Languages
- [x] Plan Worlds
- [x] Plan Groups
- [x] Plan Scenes
- [x] Add relations to all of the above
- [x] Dashboard redesign
- [ ] Language word lists
- [x] Custom fields

### CODE REVIEW

**Comment by mpigsley** [comment]
Just ran this branch and noticed the uncapitalized favorites. Might need to update the english locale dictionary.
screen shot 2016-10-23 at 3 16 55 pm

**Comment by mpigsley** [comment]
Also, thoughts on removing or resizing the right column at the large content size to avoid things like this:

screen shot 2016-10-23 at 3 19 55 pm
screen shot 2016-10-23 at 3 22 02 pm

**Comment by drusepth** [comment]
@mpigsley Good catches all around. I think at the large content size we're safe expanding the right column from l2 to l3. I know a lot of people like the serendipitous cards there, and I want to make sure they're still prominent. Though I do think moving stuff around might be a better long-term solution to maximize space for actual content. I'll just increase the sidebar width for now and we can move things around as need be.

**Comment by drusepth** [comment]
We're live!

**Pull request merged**
