### PR TITLE
Adding a few keyboard commands as well as a simple dialog to give help

### PR DESCRIPTION
**Pull request by andrewcarreiro**
For issue #121 

Tested on:
- Safari (OSX El Capitan)
- Chrome (OSX El Capitan)
- Chrome (Windows 10)
- Firefox (OSX El Capitan)
- Internet Explorer (Windows 10)

I didn't include tab navigation in this one, because it requires a bit more work since the tab system is currently just using hashes.

### CODE REVIEW

**Comment by Cantido** [comment]
Beautiful work! The only nit-picking I have is on the missing end-of-file newlines. Besides that, I'd be happy to give it my approval, as soon as I can play with it on my desktop when I get home.

**Comment by andrewcarreiro** [comment]
@Cantido Do you prefer me squashing/force pushing to my repo to add them, or creating a second commit adding newlines?

**Comment by Cantido** [comment]
Adding a second commit is fine, I make a mess of my own branches and it hasn't been a problem lol

**Comment by drusepth** [comment]
@andrewcarreiro I'm happy to merge this as soon as you update it with master. :+1:

**Comment by andrewcarreiro** [comment]
Totally missed this! Rebased on your master + forced pushed to my branch.

**Comment by Cantido** [comment]
I re-ran the build, the failure wasn't your fault, it's mine and i need to get around to fixing it (in #138).

**Comment by drusepth** [comment]
Ready to rock 'n roll! Will tweet out a note about this feature also. :)

**Pull request merged**
