### PR TITLE
Docker configuration for local development

### PR DESCRIPTION
**Pull request by andrewcarreiro**
So while I was working on https://github.com/indentlabs/notebook/pull/127 I ended up creating this Docker setup since my machine was giving me shit with RVM.

It might make things easier for new people to contribute, since it automates all the steps and doesn't pollute your local machine with specific versions of ruby or gems.

### CODE REVIEW

**Comment by Cantido** [comment]
Great idea; I was basically unable to work on this app while I was on a Windows machine. Ruby is a pain unless you're on Linux or Mac. We'd have to look into how Heroku handles Docker containers, but it shouldn't be hard.

**Comment by drusepth** [comment]
I like this, though we should probably change those `notepad-ai` references to `notebook-ai` ;)

Also, I think as long as Heroku doesn't try to spin up Docker containers just because we have a Docker file, this'll be a great addition for people wanting to get set up quickly locally.

**Comment by andrewcarreiro** [comment]
Fixed it so it actually uses the project name, and added newlines :)

**Comment by Cantido** [comment]
It looks like you need to jump through some extra hoops to get Heroku to deploy a Docker container, so I think we're good there.

**Comment by drusepth** [comment]
In that case, awesome! Looks like it'll be helpful.

**Pull request merged**
