### PR TITLE
Internationalize the app

### PR DESCRIPTION
**Pull request by Cantido**
We have a very kind person who has offered to translate the app into Spanish. In order for that to be possible, the site needs to be internationalized. All strings must be extracted into `en.yml`.

### CODE REVIEW

**Comment by Lobachevskiy** [comment]
Depending on how busy I am at the time, I could do Russian translation when this is ready.

**Comment by Cantido** [comment]
@Lobachevskiy that would be wonderful, thank you! I'll definitely keep this pull request updated so you can know when we're set for translations. I think this is near-finished, but other pull requests are making big changes so I need to wait til those are integrated.

**Comment by StorytellerCZ** [comment]
When ready, ping me. I'm willing to do a Czech translation.

**Comment by Cantido** [comment]
Since the app has moved on so much since I opened this PR, I'm going to close this. Sorry about that.

**Comment by drusepth** [comment]
I appreciate the effort, @Cantido, and am thankful to everyone who offered to translate the app. Unfortunately with GDPR in effect now, I'm not sure we'll be able to internationalize the app until after I've spoken to a GDPR compliance expert, which are still prohibitively expensive. Hopefully someday, though.

**Pull request closed without merging**
