### PR TITLE
Various Style Tweaks

### PR DESCRIPTION
**Pull request by mpigsley**
## Descriptions
Fixed some styling issues at different viewport widths.

### User Content
At larger widths the user profile content section was too skinny to have to have two elements per row. At the medium and large widths the sections are now only one element per column.

screen shot 2016-10-12 at 2 39 45 pm

At the mobile width the content is still set at two per row.

screen shot 2016-10-12 at 2 40 10 pm

### Active Universe Button on Mobile
Previously the button exceeded the height of the nav on mobile.

screen shot 2016-10-12 at 2 54 30 pm

And now it matches the height.

screen shot 2016-10-12 at 2 54 43 pm

### Dropdown Padding/Margin Tweaks (again)
At smaller widths the dropdowns don't match the spacing of the other input elements. Now they will be matched.

screen shot 2016-10-12 at 2 56 52 pm

### Weird Wrapping with Relation Content
screen shot 2016-10-15 at 9 38 19 am

Now they wrap as expected by matching the max-height of the other input elements.

screen shot 2016-10-15 at 1 55 25 pm

### CODE REVIEW

**Comment by mpigsley** [comment]
Not sure exactly what's up with that failing test. I didn't update `cards/serendipitous/content_question`.

**Comment by Cantido** [comment]
Sorry, that card shows random questions, but occasionally that card doesn't show if there isn't a question configured for the field it picks. I just re-ran the build, it should pass. I just created #138 to track it.

**Comment by mpigsley** [comment]
Will do @Cantido !

**Comment by Cantido** [comment]
@drusepth is the only one who can merge changes to master, so I've assigned this to him :)

**Comment by drusepth** [comment]
These are very well-appreciated design tweaks (specifically the field wrapping). I'll get them merged to master and merged to the `content-expansion` branch, which has lots of upcoming UI changes as well. :+1:

**Pull request merged**
