### PR TITLE
[WIP] Delete relation objects when objects owning them are deleted

### LINKED ISSUE #190: Relation objects aren't deleted when the objects owning them are deleted
To reproduce:

* Create a character Alice and a separate character Bob
* Link Bob as Alice's sibling in the Family tab
* Delete both Bob and Alice
* You will see 2 Siblingship objects remain in the database.

Expected:

* These Siblingship objects should be deleted when either of the related objects are deleted

Note:

* Deleting either Alice or Bob should also delete both Siblingship objects, but should obviously not delete the Alice character (if deleting Bob) or the Bob character (if just deleting Alice).

The fix should include test(s) for the above cases.

[Bountysource](https://www.bountysource.com/issues/42411724-relation-objects-aren-t-deleted-when-the-objects-owning-them-are-deleted?utm_source=42411724&utm_medium=shield&utm_campaign=ISSUE_BADGE)

### PR DESCRIPTION
**Pull request by babu-thomas**
Fixes #190 

@drusepth , continuing our discussion from issue tracker here as its easier to show changes.
I checked the case for `mother` relation. The `Mothership` objects were not being deleted on deletion of mother character. Here's what I did -
1. Create characters Carol and David
2. Mark Carol as David's mother
    * As expected this creates a `Mothership` and `Childrenship` object.
3. Delete Carol
    * `Childrenship` object is deleted but `Mothership` object remains in the database.

Changes proposed:
  * Inside `Childrenship` the reverse association was not being deleted when the gender of character was not set. Now it searches in `fathers` and then in `mothers` for the reverse association and deletes it. After this change the `Mothership` object gets deleted as required on deleting mother or child. I also tested `Fathership` and it works.

Further questions:
  * During creation of `Childrenship` too the reverse association is not created if gender of character is not set. How should I handle this? Should there be a default as mother (or father) or gender should be mandatory for linking children?

### CODE REVIEW

**Comment by drusepth** [comment]
Hey, sorry about the delay on this. Good catch, and good fix. Based on that solution, we should probably be mindful of any two-way associations we create just to make sure they get properly deleted both-ways when either end is deleted. Having to do it manually per association is less than ideal, but not the worst thing, so this looks reasonable. 

To answer your question:

Right now, since a "child" isn't generally tied to a gender like a "mother" or "father" is (e.g. we aren't splitting children into sons/daughters), we don't try to guess the gender to create the reverse relation when the child's gender is not set.

As a concrete example:

* Someone creates Little Alice
* Someone creates Dad Bob, but doesn't give him/her a gender
* Someone, while editing Dad Bob, sets Little Alice as his/her child
  * This creates a Childrenship object saying Little Alice is Dad Bob's child
  * There is then ambiguity between whether to create the reverse relationship as a Fathership or a Mothership, since Dad Bob doesn't have a gender specified
    * (We don't want to try to guess by name here, since s/he could very well just be named X or something)

I think the ideal approach is to introduce another relationship of "Parentship" that is created (and displayed in the UI) in such a case, so gender isn't necessary, and can be replaced with the proper Mothership/Fathership whenever a gender is set later. I think that's a bit out of scope for this PR though, so the current implementation looks good. We can circle back to Parentships in another issue.

The only thing I'd recommend adding before this is ready to merge is a few simple tests automating what you've been testing manually:

* Deleting one character deletes its associations -- we can just use fathership/childrenship here
  * The other characters in those associations are not deleted
  * The associations on those other characters (fatherships, childrenships) that reference the deleted character are also deleted

Does that make sense? Thanks again!

**Comment by babu-thomas** [comment]
> To answer your question:...

Thanks for clearing that up!

> The only thing I'd recommend adding before this is ready to merge is a few simple tests automating what you've been testing manually

I will work on adding tests now. Will update PR when its done.

**Comment by babu-thomas** [comment]
I'm sorry this is taking so long. I will try to get it done this weekend.

**Comment by babu-thomas** [comment]
Hi @druspeth. I have added tests for sibling relation. The added tests pass on my branch and fail on master as expected. Once these tests are reviewed, I will add tests for Fathership/Childrenship.

This is the first time I am writing any kind of test in Rails, so all feedback is gladly welcome. RSpec was a little confusing with so many ways to do things(let vs before, describe vs context, etc). I hope I did alright.

Thanks in advance!

**Comment by drusepth** [comment]
Hey @babu-thomas, no worries. Sorry I didn't see the ping above until just now. 

I went ahead and merged in `master` (in which the latest has passing tests) so we should see the tests passing now. I'll take a look at the tests and leave comments if I've got any! 👍

**Comment by drusepth** [comment]
I'm actually not sure why the tests are still failing -- they're passing for me locally. Could you try running `bundle exec rake spec` locally and see if you get any failures?

In terms of the tests, they look perfect: very short and to the point, testing exactly one thing at a time. That's exactly what I was looking for. I'm also not 100% sure on some of the differences in ways to do thing in RSpec (e.g. context vs describe), but you did a good job of conforming to whatever was being used already. :)

For reference though, as I understand it, `let` is most often used to define a variable that's repeatedly used within a block of tests, like a character. For example,
```
  let(:user) { build(:user, email: 'test@example.com') }
```
creates a `user` variable in the current describe/context block (once, before running any test in that block) that can be used in any tests within the block. In contrast, I believe a `before` block is run before _each_ test in the block. 

I'm _pretty_ sure that's correct, or at least that's been the intent when writing tests here! 👍

**Comment by babu-thomas** [comment]
I just tested and running `bundle exec rake spec` gives no output. 

`bundle exec rspec` gives -
```
.......................................................................................................................................................................................

Finished in 10.42 seconds (files took 4 seconds to load)
183 examples, 0 failures
```
and `bundle exec rake` fails with the same output as on the CI server.

**Comment by drusepth** [comment]
@babu-thomas I finally got around to checking out the tests here and it looks like they're actually passing now; I imagine there was some kind of bug in master that conflicted with this PR, but has since been fixed. Will merge momentarily! 👍

**Comment by babu-thomas** [comment]
Great! @drusepth Thank you so much for your help at every step of the way.

**Pull request merged**
