### PR TITLE
GPT-3 integrations

### PR DESCRIPTION
**Pull request by drusepth**
Built on top of #738 (merge that first)

### CODE REVIEW

**Comment by drusepth** [comment]
GPT-3's pricing makes this feature prohibitively expensive. We used nearly 2M tokens in a month during testing, so we'd probably have to go with, at minimum, the $400/month plan to cover usage; maybe more to be in a comfort zone where we don't need to worry about limiting tokens used per user. 

Gonna leave this open for now, but it probably won't see the light of day. :moon:

**Comment by mrseeker** [comment]
Is it possible to convert it to use GPT-Neo?

**Comment by drusepth** [comment]
@mrseeker I haven't been following GPT-Neo, but it might be possible. This branch just uses [our gpt3-gem](https://github.com/indentlabs/gpt3-gem), so something with a similar interface for GPT-Neo might actually just be a drop-in replacement. How's the pricing with Neo?

**Comment by drusepth** [comment]
I think this is old enough that it'd worth a rewrite in gpt3.5/4 (or, better yet, our own LLM), but this existing WIP implementation isn't worth keeping around.

**Pull request closed without merging**
