### PR TITLE
Migrate tests to rspec and cucumber

### PR DESCRIPTION
**Pull request by Cantido**
Here's what I hope to do:

 - [x] Migrate all unit & controller tests into rspec
 - [x] Migrate all integration tests into cucumber

And, depending on how I feel:

 - [x] Write basic cucumber scripts to cover the major functionality of the website

### CODE REVIEW

**Comment by Cantido** [comment]
Unit & controller tests are done. Now I'll be writing Cucumber features that can navigate the site and perform some user stories.

**Comment by Cantido** [comment]
@drusepth ready for review

**Comment by drusepth** [comment]
Ready to ship :ship:

**Comment by drusepth** [comment]
Deploying this while forcing a restart of the app.

**Pull request merged**
